### ISSUE TITLE
configurable oauth api token

### ISSUE THREAD

**Issue by chrisns** [vzhd1701/evernote-backup#1]
<feature-request>
Hi, would be great to have env vars or some other runtime way to replace in https://github.com/vzhd1701/evernote-backup/blob/master/evernote_backup/config.py I'm using docker so I can naturally mount a replacement file in, but that's not ideal and won't work for those running the binary(?)

Also notes on the approach taken to get approved keys with production evernote access would be great

**Comment by vzhd1701** [comment]
Thank you for the feedback! Yes, I should make those config values into command line parameters. Do you want the ability also to use custom API keys? If you're going to use the existing OAuth token, then there is already a `--token` option for that.

> Also notes on the approach taken to get approved keys with production evernote access would be great

What exactly do you want to know? I use two different API keys, one for password login and one for OAuth. The one that I use for password login I just ripped from ENScript. As for the OAuth one, I requested activation for the sandbox key using [the form from their FAQ page](https://dev.evernote.com/support/faq.php), and they approved it after a couple of days without any questions.

**Comment by chrisns** [comment]
sorry, missed your reply!
I guess exposing any of the hardcoded keys is probably a good a good thing, you could go further to say that the use of the hardcoded keys should be something you have to do on purpose with a flag to consciously accept that, its not really clear how the magic works, and if there's any risk of doing so. i.e. as the api key owner do evernote give you any usage stats etc that I might not want to share?
Yes I saw your magic token extractor, that looks great and probably what I'll use

**Comment by vzhd1701** [comment]
fecf49aa150f3375b4a3b94b5a6ec72b2ff6a038
