### ISSUE TITLE
Request: Zero change files

### ISSUE THREAD

**Issue by robdejonge** [vzhd1701/evernote-backup#12]
At the moment, `evernote-backup` writes the exported files with an `export-date` in one of the first lines. Both in notebook export as well as the `--single-notes` version. Obviously, the value of this field changes the content of the file. This triggers backup software to either backup the entire file or chunks of it. 

I have for now removed the field from line 20 of [note_exporter.py](https://github.com/vzhd1701/evernote-backup/blob/master/evernote_backup/note_exporter.py), but obviously this is not a sustainable option. 

I was wondering if it would be possible to offer a command-line option `--no-export-date` to the export function of the program.

**Comment by vzhd1701** [comment]
Done. Please check out the new version.

**Comment by robdejonge** [comment]
Previously, each day would add 270MB to my backup volume even with no changes to Evernote made. 
With this feature implemented, each day adds just 6KB in metadata for the new revision. 

Thank you for implementing this!
