### ISSUE TITLE
How can we tip you? :-)

### ISSUE THREAD

**Issue by camflint** [vzhd1701/evernote-backup#16]
### Suggestion

Thank you for writing and maintaining this tool! It does exactly what it says it does without any fuss. Perfect.

How can we donate a few dollars or send a tip to show our appreciation?

Cheers!

**Comment by vzhd1701** [comment]
Thank you for consideration! I can accept donations in crypto only at the moment
https://bit.ly/vzhd1701_donate

**Comment by vzhd1701** [comment]
Now I can accept donations through buymeacoffee.com
https://www.buymeacoffee.com/vzhd1701
