### ISSUE TITLE
Re-Installation problem

### ISSUE THREAD

**Issue by SprickW** [vzhd1701/evernote-backup#25]
Today I upgraded from Ubuntu 20.04 to 22.04. After that evernot-backup was not found.

pipx install evernote-backup with and without --force cause errors.

cmd_2022-08-18_21.02.17_pip_errors.log shows:

PIP STDERR
----------
/home/sprickw/.local/pipx/venvs/evernote-backup/bin/python: No module named pip

[cmd_2022-08-18_21.02.17.log](https://github.com/vzhd1701/evernote-backup/files/9376806/cmd_2022-08-18_21.02.17.log)

Is there some way to fix this?

Greetings Wolfgang

**Comment by vzhd1701** [comment]
Try `pipx reinstall-all`

**Comment by SprickW** [comment]
The upgrade to Ubuntu 22.04 seems to have some strange effects on the python environment

(venv) sprickw@weser:~/Projects/evernote$ pipx reinstall-all
/home/sprickw/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/home/sprickw/.local/lib/python3.10/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/home/sprickw/.local/lib/python3.10/site-packages/pipx/util.py", line 203, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/sprickw/.local/pipx/shared/bin/python -m pip --disable-pip-version-check install -q --upgrade pip setuptools wheel' failed
(venv) sprickw@weser:~/Projects/evernote$ 

Same result with or without venv. Calling pip directly works.

I'm considering seting up my laptop from scratch ... :-(

**Comment by vzhd1701** [comment]
You don't have to set up from scratch. The problem is that pipx virutal envs got messed up because python version changed after system upgrade. Got to `~/.local/bin`, remove all shims that pipx created, then reinstall pipx.
```bash
python3 -m pip uninstall pipx
rm -rf ~/.local/pipx
python3 -m pip install --user pipx
pipx install evernote-backup
```

**Comment by SprickW** [comment]
Works perfectly! :-)
