### ISSUE TITLE
[Bug]: "OSError: [Errno 36] File name too long" after initial export 

### ISSUE THREAD

**Issue by SprickW** [vzhd1701/evernote-backup#26]
### evernote-backup version

1.9.1

### What OS are you using?

Linux

### OS Version / Linux distribution

Ubuntu 22.04

### Bug description

V1.9.1 fixed the "OSError: [Errno 36] File name too long" symptom with "evernote-backup export". But trying to update the export dir by executing the command again still leeds to this error.

**Comment by vzhd1701** [comment]
This should be fixed now. Please check out the new version (1.9.2)
