### ISSUE TITLE
[Bug]: Can't input password

### ISSUE THREAD

**Issue by Auzout** [vzhd1701/evernote-backup#28]
### evernote-backup version

1.9.2

### What OS are you using?

Windows

### OS Version / Linux distribution

Windows 10

### Python version
3.7.10

### Bug description

After I execute `evernote-backup init-db --backend china`, then I can input `Username or Email:`, but I can't input password by keyborad or paste. Nothing happened when I kick my keyboard.
If I continue to kick Enter, it show `Invalid password!`.

**Comment by vzhd1701** [comment]
This is normal behavior. The password is typing in OK, it's just not visible. Type it in when password prompt appears and press Enter.
