### ISSUE TITLE
[Feature request]: export with --overwrite flag?

### ISSUE THREAD

**Issue by arrikhan** [vzhd1701/evernote-backup#46]
### Suggestion

Currently I run a docker container with sync command daily and export command daily. The purpose is to export the data onto a backup device separate to the locally sync'd database using the sync command.

Can an '--overwrite' flag be added to enable option of overwrite files during export? Currently, running export twice writes duplicate file with (#) appended. Folders are ok.

NOTE: I'm using --single-notes mode in this instance.

**Comment by Houska1** [comment]
I agree that this would be a nice enhancement. However, if your use case is local backup in case Evernote and/or its cloud storage goes bonkers, I wonder if you need to actually export daily? I merely back up the SQLite db as updated by sync, plus the evernote-backup executable: per https://github.com/vzhd1701/evernote-backup/discussions/44, I know if I ever need the notes in html format, evernote-backup can create it from the latest saved SQLite db without needing contact with Evernote.

**Comment by vzhd1701** [comment]
`evernote-backup` already has this option
```shell
$ evernote-backup export --help
Usage: evernote-backup export [OPTIONS] OUTPUT_PATH

  Export all notes from local database into ENEX files.

Options:
  ...
  --overwrite          Overwrite existing ENEX files.
  ...
```
