### ISSUE TITLE
exception "file name to long"

### ISSUE THREAD

**Issue by SprickW** [vzhd1701/evernote-backup#8]
First thing first: Great package, will help me a LOT!

evernote-backup export --single-notes /home/xxx/somedir

leads to exception

  File "/home/sprickw/PycharmProjects/evernote/venv/lib/python3.8/site-packages/evernote_backup/note_exporter.py", line 122, in _write_export_file
    with open(file_path, "w", encoding="utf-8") as f:
OSError: [Errno 36] File name too long: 

Looking into the code the reason is clear: the notes title is simply too long.

Probable simple solution: just shorten the file name part of the path to 255 chars. Maybe even better: calculate some crc32 (or similar) from title and content, shorten the filename and and the hash at its end, finally adding ".enex".

**Comment by RhetTbull** [comment]
I've implemented a proposed fix and will submit a PR shortly.

**Comment by RhetTbull** [comment]
I got the same issue with a couple notes with ridiculously long titles (clipped web pages).  I got around it by finding the notes in Evernote, shortening the titles, doing a `evernote-backup sync` then re-exporting.  The PR I submitted will trim the file names (whilst preserving the extension) if too long.

**Comment by vzhd1701** [comment]
Fixed now. Big thanks to @RhetTbull !!
Happy new year to you guys!

**Comment by RhetTbull** [comment]
Happy New Year to you as well and Thank You for such a useful tool!
